# Generated by Django 6.0.1 on 2026-01-21 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('HR', 'HR'), ('EMPLOYEE', 'Employee')], default='Employee', max_length=20),
        ),
    ]
